-- liquibase formatted sql

-- changeset YuriiYatsenko:1
CREATE TABLE person_info
(
    id           BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    address      VARCHAR(255) NULL,
    photo        oid          NULL,
    email        VARCHAR(255) NULL,
    first_name   VARCHAR(255) NOT NULL,
    last_name    VARCHAR(255) NOT NULL,
    passport     VARCHAR(255) NULL,
    phone_number VARCHAR(255) NOT NULL,
    CONSTRAINT person_info_PK PRIMARY KEY (id)
);

CREATE TABLE person
(
    id        BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    chat_id   BIGINT       NOT NULL,
    state     VARCHAR(255) NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    info_id   BIGINT       NULL,
    CONSTRAINT person_PK PRIMARY KEY (id),
    CONSTRAINT FK_person_info_constraint FOREIGN KEY (info_id) REFERENCES person_info (id)
);

CREATE TABLE shelter
(
    id      BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    address VARCHAR(255) NULL,
    photo   oid          NULL,
    "name"  VARCHAR(255) NULL,
    "type"  VARCHAR(255) NULL,
    CONSTRAINT shelter_PK PRIMARY KEY (id)
);

CREATE TABLE pet
(
    id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    age         INTEGER      NULL,
    breed       VARCHAR(255) NULL,
    photo       oid          NULL,
    description VARCHAR(255) NULL,
    gender      VARCHAR(255) NULL,
    "name"      VARCHAR(255) NULL,
    "type"      VARCHAR(255) NULL,
    shelter_id  BIGINT       NOT NULL,
    owner_id    BIGINT       NOT NULL,
    CONSTRAINT pet_PK PRIMARY KEY (id),
    CONSTRAINT FK_person_constraint FOREIGN KEY (owner_id) REFERENCES person (id),
    CONSTRAINT FK_shelter_consraint FOREIGN KEY (shelter_id) REFERENCES shelter (id)
);

-- changeset RomanZeleinin:1
ALTER TABLE pet
    ALTER COLUMN owner_id DROP NOT NULL;
ALTER TABLE pet
    ALTER COLUMN shelter_id DROP NOT NULL;

-- changeset RomanZelenin:2
ALTER TABLE shelter
    ADD description VARCHAR(255) NULL;

-- changeset RomanZelenin:3
ALTER TABLE shelter
    ADD preview VARCHAR(255) NULL;

-- changeset RomanZelenin:4
ALTER TABLE person
    ADD COLUMN shelter_id BIGINT,
    ADD CONSTRAINT fk_shelter_id
        FOREIGN KEY (shelter_id)
            REFERENCES shelter (id)
            ON DELETE CASCADE;

-- changeset RomanZelenin:5
ALTER TABLE person
    DROP CONSTRAINT fk_shelter_id,
    ADD CONSTRAINT fk_shelter_id
        FOREIGN KEY (shelter_id)
            REFERENCES shelter (id)
            ON DELETE SET NULL;

-- changeset YuriiYatsenko:2
ALTER TABLE shelter
    ALTER COLUMN description TYPE VARCHAR(2000);
ALTER TABLE shelter
    ADD schema oid NULL;
ALTER TABLE shelter
    ADD schedule VARCHAR(255) NULL;
ALTER TABLE shelter
    ADD security_phone VARCHAR(255) NULL;
ALTER TABLE shelter
    ADD safety_rules VARCHAR(1000) NULL;
-- changeset YuriPet:1
CREATE TABLE adoption_record
(
id               BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
pet_id           BIGINT       NOT NULL,
user_id          BIGINT       NOT NULL,
adoption_date    DATE         NULL,
trial_period_end DATE         NULL,
trial_period_days INTEGER     NULL,
state            VARCHAR(255) NULL,
rating_total     INTEGER      NULL,
CONSTRAINT adoption_record_PK PRIMARY KEY (id),
CONSTRAINT FK_pet_constraint FOREIGN KEY (pet_id) REFERENCES pet (id),
CONSTRAINT FK_user_constraint FOREIGN KEY (user_id) REFERENCES person (id)
);

CREATE TABLE report
(
id                   BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
report_date_time     DATE         NULL,
rating_total         INTEGER      NULL,
adoption_record_id   BIGINT       NULL,
data                 BYTEA        NULL,
photo                oid          NULL,
CONSTRAINT report_PK PRIMARY KEY (id),
CONSTRAINT FK_adoption_record_constraint FOREIGN KEY (adoption_record_id) REFERENCES adoption_record (id)
);

-- changeset YuriPet:2
ALTER TABLE report
ADD COLUMN diet_appetite INTEGER CHECK (diet_appetite >= 0 AND diet_appetite <= 10),
ADD COLUMN diet_preferences INTEGER CHECK (diet_preferences >= 0 AND diet_preferences <= 10),
ADD COLUMN diet_allergies INTEGER CHECK (diet_allergies >= 0 AND diet_allergies <= 10),
ADD COLUMN health_status INTEGER CHECK (health_status >= 0 AND health_status <= 10),
ADD COLUMN behavior_change INTEGER CHECK (behavior_change >= 0 AND behavior_change <= 10);

-- changeset YuriPet:3
ALTER TABLE person
    ADD COLUMN adoption_record_id BIGINT,
    ADD CONSTRAINT fk_adoption_record_person
        FOREIGN KEY (adoption_record_id)
            REFERENCES adoption_record (id)
            ON DELETE SET NULL;

ALTER TABLE pet
    ADD COLUMN adoption_record_id BIGINT,
    ADD CONSTRAINT fk_adoption_record_pet
        FOREIGN KEY (adoption_record_id)
            REFERENCES adoption_record (id)
            ON DELETE SET NULL;